### ISSUE TITLE
fonttbl is output as HTML

### ISSUE THREAD

**Issue by PhenX** [Anastaszor/PhpRtfToHtml#1]
When using this code:

```php
<?php

include "src/autoload.php";

$document = new Rtfparser();
$document->parse(file_get_contents("../sample.rtf"));

$writer = new RtfHtml();
echo $writer->Format($document->root);
```

With the attached [sample file (you need to rename it to rtf)](https://github.com/Anastaszor/PhpRtfToHtml/files/83639/sample.txt), the fonttbl content is displayed.

Note that the picture too.

**Comment by Anastaszor** [comment]
Bonjour, 

As you can see, there is a large number of things broken from the time i took this library and modified it to fit my needs. Even the naming convention is broken. And there is a large amount of work required to have a perfect rtf -> html conversion, which can only be done step by step. 

I think commit 2379162e3e383e466d3e87c1d6f904f89989caa4 partially solves this specific issue : the fonttbl content is not displayed anymore, and is completely ignored. A better way to do that should be to better parse elements, converts them to html structure and then formats them into inline css to the header of the html document.

**Comment by PhenX** [comment]
Great ! Thank you, I'll give it a try. 
I looked for a lot of similar libraries to display RTF files, but didn't find any as complete as yours.
And to finish, are you French ? because I am :)

**Comment by Anastaszor** [comment]
Thank you.
I recommand directly jump to last commit as it also corrects a bug about the first character of texts being eaten by the parser... I'm really surprised there exists no library that does better in php.

And yes, i'm French also. But i'm still written in english as i think it's easier for more people to understand. :)

Do you consider this issue to be solved ? If so could you close it ? I'd gladly try to solve other issues if there are more specific needs to fulfill.

**Comment by PhenX** [comment]
Yes that's OK for me, but there is another issue, maybe not related to this one, I'll open a new one.

Thanks !
